env:
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - 2
  quotes:
    - double
  semi:
    - error
    - never
  no-constant-condition:
    - false
